name: AutoMineReset
main: Example\Example
version: 0.1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
commands:
 mr:
  description: "Short command to reset all mines!"
  usage: "/mr"
  permission: minereset.command.resetall
