name: AutoMineReset
main: AndreasHGK\AutoMineReset\Main
version: 0.2.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
commands:
 mr:
  description: "Short command to reset all mines!"
  usage: "/mr"
  permission: minereset.command.resetall
 autoreset:
  description: "Enable / disable autoreset"
  usage: "/autoreset"
  permission: amr.autoreset
